- person:
  - keys:
    - id, int
  - fields:
    - name, varchar
    - family, varchar
  - links:
    - person.id-car.personid
    - person.id-house.personid
- car:
  - keys:
    - id, int
  - fields:
    - personid, int
    - cartype, varchar
    - color, varchar
- house:
  - keys:
    - id, int
  - fields:
    - personid, int
    - price, numeric
    - rooms, int 
    - inches, numeric
